### ISSUE TITLE
pip install needs sudo

### ISSUE THREAD

**Issue by ilg-ul** [kvasir-io/HardwareDescriptionFileGenerator#12]
I tried to follow **exactly** the steps in the README, but did not get too far:

```
ilg-mbp:HardwareDescriptionFileGenerator ilg$ pip install bs4 empy lxml
Collecting bs4
  Downloading bs4-0.0.1.tar.gz
Collecting empy
  Downloading empy-3.3.2.tar.gz (138kB)
    100% |████████████████████████████████| 143kB 1.4MB/s 
Collecting lxml
  Downloading lxml-3.7.3.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 100kB/s 
Requirement already satisfied: beautifulsoup4 in /Library/Python/2.7/site-packages (from bs4)
Building wheels for collected packages: bs4, empy, lxml
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /Users/ilg/Library/Caches/pip/wheels/84/67/d4/9e09d9d5adede2ee1c7b7e8775ba3fbb04d07c4f946f0e4f11
  Running setup.py bdist_wheel for empy ... done
  Stored in directory: /Users/ilg/Library/Caches/pip/wheels/1f/8b/df/8abfea04cbbe0eef3c36fb00bb0a8de84d86e05aca029516af
  Running setup.py bdist_wheel for lxml ... done
  Stored in directory: /Users/ilg/Library/Caches/pip/wheels/df/32/5f/0acd510ac7d66ebe5f35155508972fa732ec45acd5f79146d2
Successfully built bs4 empy lxml
Installing collected packages: bs4, empy, lxml
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/bs4-0.0.1.dist-info'
ilg-mbp:HardwareDescriptionFileGenerator ilg$ 
```

you should recommend to use `sudo`.

also, if after cloning the folder you need to update modules, you should list the commands to do so, don't expect users to remember everything by heart. I personally used GitHubDesktop, I hope it does everything automatically.

**Comment by ilg-ul** [comment]
some more:

```
ilg-mbp:HardwareDescriptionFileGenerator ilg$ sudo python2 setup.py install
sudo: python2: command not found
ilg-mbp:HardwareDescriptionFileGenerator ilg$ sudo python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory
ilg-mbp:HardwareDescriptionFileGenerator ilg$ sudo python src/setup.py install
running install
running build
running build_py
error: package directory 'svd_parser' does not exist
cd src
ilg-mbp:src ilg$ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/svd_parser
copying svd_parser/__init__.py -> build/lib/svd_parser
copying svd_parser/format_utils.py -> build/lib/svd_parser
copying svd_parser/parse_device.py -> build/lib/svd_parser
copying svd_parser/parser_utils.py -> build/lib/svd_parser
copying svd_parser/validate_schema.py -> build/lib/svd_parser
running install_lib
creating /Library/Python/2.7/site-packages/svd_parser
copying build/lib/svd_parser/__init__.py -> /Library/Python/2.7/site-packages/svd_parser
copying build/lib/svd_parser/format_utils.py -> /Library/Python/2.7/site-packages/svd_parser
copying build/lib/svd_parser/parse_device.py -> /Library/Python/2.7/site-packages/svd_parser
copying build/lib/svd_parser/parser_utils.py -> /Library/Python/2.7/site-packages/svd_parser
copying build/lib/svd_parser/validate_schema.py -> /Library/Python/2.7/site-packages/svd_parser
byte-compiling /Library/Python/2.7/site-packages/svd_parser/__init__.py to __init__.pyc
byte-compiling /Library/Python/2.7/site-packages/svd_parser/format_utils.py to format_utils.pyc
byte-compiling /Library/Python/2.7/site-packages/svd_parser/parse_device.py to parse_device.pyc
byte-compiling /Library/Python/2.7/site-packages/svd_parser/parser_utils.py to parser_utils.pyc
byte-compiling /Library/Python/2.7/site-packages/svd_parser/validate_schema.py to validate_schema.pyc
running install_egg_info
Writing /Library/Python/2.7/site-packages/svd_parser-0.1-py2.7.egg-info
ilg-mbp:src ilg$ cd ..
ilg-mbp:HardwareDescriptionFileGenerator ilg$ mkdir build
ilg-mbp:HardwareDescriptionFileGenerator ilg$ cd build
ilg-mbp:build ilg$ 
ilg-mbp:build ilg$ cmake .. -DBUILD_TESTING=1
-bash: cmake: command not found
ilg-mbp:build ilg$ 
```

(that's exactly for these reasons that I gave up using python and switched to node).

later on after installing cmake, I got tons of warnings like:

```
CMake Warning at cmake/hdfg_generate_device.cmake:22 (message):
  Tried to add target MB9AF10xN_generated which already exists.
Call Stack (most recent call first):
  cmake/hdfg_generate_targets_for_directory.cmake:31 (hdfg_generate_device)
  CMakeLists.txt:39 (hdfg_generate_targets_for_directory)


CMake Warning at cmake/hdfg_generate_device.cmake:22 (message):
  Tried to add target MB9AF10xR_generated which already exists.
Call Stack (most recent call first):
  cmake/hdfg_generate_targets_for_directory.cmake:31 (hdfg_generate_device)
  CMakeLists.txt:39 (hdfg_generate_targets_for_directory)
```

(I wonder what is the reason why I was never able to get even close to cmake...)

please update the README.
